
name: SAMA-VQA-sama
test_batch_size: 1
test_num_workers: 2

stype: sama  # [sama, sama-c, sama-mix, sama-swm, sama-spm, fragments==others]

data:
    val-ltest:
        type: FusionDataset
        args:
            phase: test
            anno_file: ./examplar_data_labels/LSVQ/labels_mytest.txt
            data_prefix: PATH_TO_DATA/LSVQ
            sample_types:
                fragments:
                    fragments_h: 7
                    fragments_w: 7
                    fsize_h: 32
                    fsize_w: 32
                    aligned: 32
                    clip_len: 32
                    frame_interval: 2
                    num_clips: 4 
model:
    type: DiViDeAddEvaluator
    args:
        backbone:
            fragments:
                checkpoint: false
                pretrained: 
        backbone_size: swin_tiny_grpb
        backbone_preserve_keys: fragments
        divide_head: false
        vqa_head:
            in_channels: 768
            hidden_channels: 64
            
optimizer:
    lr: !!float 1e-3
    backbone_lr_mult: !!float 1e-1
    wd: 0.05
        
load_path: ./pretrained_weights/SAMA-baseline_val-ltest_s_dev_v0.0.pth
