# Swin-Image-Encoder for IQA

name: SAMA-IQA-sama-koniq

stype: sama  # [fragment, sama, sama-spm]

num_epochs: 50
l_num_epochs: 0
warmup_epochs: 5
constant_epochs: 150
ema: true
save_model: true
batch_size: 64  # 64  
num_workers: 8
test_batch_size: 64  #64
test_num_workers: 8
num_splits: 10

data:
    database: koniq
    data_info: PATH_TO_DATA/koniq/koniq10k_scores.csv
    data_prefix: PATH_TO_DATA/data/koniq/1024x768

    fwin_h: 8
    fwin_w: 8
    fsize_h: 32
    fsize_w: 32


# data:
#     database: spaq
#     data_info: PATH_TO_DATA/spaq/spaq_info.txt
#     data_prefix: PATH_TO_DATA/spaq/TestImage

#     fwin_h: 8
#     fwin_w: 8
#     fsize_h: 32
#     fsize_w: 32


# model: # discard
#     backbone_type: swin_image_v2
#     head_in_channels: 768
#     head_hidden_channels: 128
            
optimizer:
    lr: !!float 1e-3
    backbone_lr_mult: !!float 1e-1
    wd: 0.05
    
load_path: PATH_TO_MODEL/swinv2_tiny_patch4_window8_256.pth
